--insert into PERFILESJOSEGONZALEZ (RUT,NOMBRE,APPAT,APMAT,CLAVE) values ()


select * from PERFILESJOSEGONZALEZ
select * from ACCIONESJOSEGONZALEZ


select clave from PERFILESJOSEGONZALEZ where RUT = '18247430-4'
delete from ACCIONESJOSEGONZALEZ

insert into ACCIONESJOSEGONZALEZ (CLAVE,INICIOSESION, FINSESION,ACCION,ACCIONF)

select * from PERFILESJOSEGONZALEZ where APPAT = 'Gonzalez'

